name: category_smash
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  equatable: ^2.0.5
  flex_color_picker: ^3.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  pausable_timer: ^3.1.0+3
  provider: ^6.1.2
  shared_preferences: ^2.3.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
